{
 "title": "vLLM (Gemma3:27B) Dashboard",
 "tags": [ "Display" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Throughput (tokens per seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "data = from(bucket: \"vllm-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"prometheus\")\n  |> filter(fn: (r) => r._field == \"vllm:prompt_tokens_total\")\n  |> drop(columns: [\"engine\", \"model_name\", \"url\"])\n  |> derivative(unit: 1s, nonNegative: true)\n\nprompt_min = data\n  |> aggregateWindow(every: v.windowPeriod, fn: min)\n  |> rename(columns: {_value: \"prompt_min\"})\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\n  |> yield(name: \"prompt_min\")\n\nprompt_mean = data\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> rename(columns: {_value: \"prompt_mean\"})\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\n  |> yield(name: \"prompt_mean\")\n\nprompt_max = data\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n  |> rename(columns: {_value: \"prompt_max\"})\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\n  |> yield()\n"
    },
    {
     "query": "data = from(bucket: \"vllm-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"prometheus\")\n  |> filter(fn: (r) => r._field == \"vllm:generation_tokens_total\")\n  |> drop(columns: [\"engine\", \"model_name\", \"url\"])\n  |> derivative(unit: 1s, nonNegative: true)\n\ngeneration_min = data\n  |> aggregateWindow(every: v.windowPeriod, fn: min)\n  |> rename(columns: {_value: \"generation_min\"})\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\n  |> yield(name: \"generation_min\")\n\ngeneration_mean = data\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\n  |> rename(columns: {_value: \"generation_mean\"})\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\n  |> yield(name: \"generation_mean\")\n\ngeneration_max = data\n  |> aggregateWindow(every: v.windowPeriod, fn: max)\n  |> rename(columns: {_value: \"generation_max\"})\n  |> drop(columns: [\"_start\", \"_stop\", \"_field\"])\n  |> yield(name: \"generation_max\")\n"
    }
   ]
  },
  {
   "title": "Request Decode Time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "data = from(bucket: \"vllm-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"prometheus\")\n  |> filter(fn: (r) => r._field == \"vllm:request_decode_time_seconds_bucket\")\n  |> drop(columns: [\"engine\", \"model_name\", \"url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> difference()\n  |> map(fn: (r) => ({\n      r with le: float(v: r.le)\n    }))\n  |> group(columns: [\"_time\"]) // Group by time to ensure quantile is computed per window\n\np50 = data\n  |> histogramQuantile(quantile: 0.5)\n  |> group() // Ensure only necessary columns are grouped\n  |> rename(columns: {_value: \"p50\"})\n  |> yield(name: \"p50\")\n\n\np90 = data\n  |> histogramQuantile(quantile: 0.9)\n  |> group() // Ensure only necessary columns are grouped\n  |> rename(columns: {_value: \"p90\"})\n  |> yield(name: \"p90\")\n\np99 = data\n  |> histogramQuantile(quantile: 0.99)\n  |> group() // Ensure only necessary columns are grouped\n  |> rename(columns: {_value: \"p99\"})\n  |> yield(name: \"p99\")\n"
    }
   ]
  },
  {
   "title": "Prompt Token",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"vllm-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vllm:prompt_tokens_total\")\n  |> difference(nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    },
    {
     "query": "from(bucket: \"vllm-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vllm:prompt_tokens_total\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> rename(columns: {_value: \"new_tokens\"})\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Generation Token Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"vllm-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vllm:generation_tokens_total\")\n  |> drop(columns: [\"engine\", \"model_name\", \"url\"])\n  |> difference(nonNegative: true)\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"new_tokens\")"
    },
    {
     "query": "from(bucket: \"vllm-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vllm:generation_tokens_total\")\n  |> drop(columns: [\"engine\", \"model_name\", \"url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> rename(columns: {_value: \"total_tokens\"})\n  |> yield(name: \"total_tokens\")"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"vllm-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vllm:num_requests_running\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"vllm-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vllm:num_requests_waiting\")\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "HTTP Response Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "count" } },
   "targets": [
    {
     "query": "from(bucket: \"vllm-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"http_requests_total\" and r[\"status\"] != \"2xx\")\n  |> difference()\n  |> drop(columns: [\"url\", \"handler\", \"method\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"not-2xx\"})\n  |> yield(name: \"not-2xx\")"
    },
    {
     "query": "from(bucket: \"vllm-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"http_requests_total\" and r[\"status\"] == \"2xx\")\n  |> difference()\n  |> drop(columns: [\"url\", \"handler\", \"method\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> rename(columns: {_value: \"2xx\"})\n  |> yield(name: \"2xx\")"
    }
   ]
  },
  {
   "title": "Python GC Collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"vllm-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"python_gc_collections_total\")\n  |> difference(nonNegative: true)\n  |> drop(columns: [\"url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "GPU Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"vllm-metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"prometheus\")\n  |> filter(fn: (r) => r[\"_field\"] == \"vllm:gpu_cache_usage_perc\")\n  |> drop(columns: [\"engine\", \"model_name\", \"url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: max, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}